"""empty message

Revision ID: 57b9788bfb57
Revises: None
Create Date: 2014-11-07 09:42:55.599163

"""

# revision identifiers, used by Alembic.
revision = '57b9788bfb57'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('character', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.String(length=32), nullable=True),
    sa.Column('words', sa.String(length=150), nullable=True),
    sa.Column('wechat', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
